version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.9.4
    working_directory: /go/src/github.com/mboogerd/slack-scraper
    steps:
      - checkout
      - run: go test
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      # Write the circleci GCP service account key to disk
      - run: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
      # Authenticate this GCloud client as circleci service account
      - run: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      # Set the project to the one configured in the environment
      - run: gcloud config set project $GCLOUD_PROJECT
      # Finally, run the deploy
      - run: gcloud app deploy app.yaml --no-promote --no-stop-previous-version --log-http --verbosity=debug
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - test
      # - healthcheck:
      #     requires:
      #       - deploy
      # - promote:
      #     requires:
      #       - healthcheck